# Generated by Django 5.2.4 on 2025-07-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfile_project_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='projectfile',
            old_name='created',
            new_name='created_at',
        ),
    ]
